---
title: "Assignment 4"
output: html_document
date: "2025-03-19"
---

## Assignment 4

### Downloading all necessary files
```{r}
library(rtracklayer)

dir.create("peaks")
download.file("https://www.encodeproject.org/files/ENCFF179FJG/@@download/ENCFF179FJG.bed.gz", "p300.bed.gz")

download.file("https://www.encodeproject.org/files/ENCFF974BMC/@@download/ENCFF974BMC.bed.gz", "H3K4me3.bed.gz")

download.file("https://www.encodeproject.org/files/ENCFF426IIV/@@download/ENCFF426IIV.bed.gz", "H3K4me1.bed.gz")

download.file("https://www.encodeproject.org/files/ENCFF274UIB/@@download/ENCFF274UIB.bed.gz", "H3K27ac.bed.gz")

download.file("https://www.encodeproject.org/files/ENCFF008XKX/@@download/ENCFF008XKX.bed.gz", "H3K27me3.bed.gz")
```

### Overlap clculations
```{r}
# Getting the peaks of p300 and each histone modifications
peaks_p300 <- rtracklayer::import("p300.bed.gz", format = "narrowPeak")
export(peaks_p300, "peaks/p300.narrowPeak", format = "narrowPeak")

peaks_H3K4me3 <- rtracklayer::import("H3K4me3.bed.gz", format = "narrowPeak")
export(peaks_H3K4me3, "peaks/H3K4me3.narrowPeak", format = "narrowPeak")

peaks_H3K4me1 <- rtracklayer::import("H3K4me1.bed.gz", format = "narrowPeak")
export(peaks_H3K4me1, "peaks/H3K4me1.narrowPeak", format = "narrowPeak")

peaks_H3K27ac <- rtracklayer::import("H3K27ac.bed.gz", format = "narrowPeak")
export(peaks_H3K27ac, "peaks/H3K27ac.narrowPeak", format = "narrowPeak")

peaks_H3K27me3 <- rtracklayer::import("H3K27me3.bed.gz", format = "narrowPeak")
export(peaks_H3K27me3, "peaks/H3K27me3.narrowPeak", format = "narrowPeak")

# Compute number of overlapping peaks
overlap_H3K4me3  <- sum(overlapsAny(peaks_p300, peaks_H3K4me3, type="within"))
overlap_H3K4me1  <- sum(overlapsAny(peaks_p300, peaks_H3K4me1, type="within"))
overlap_H3K27ac  <- sum(overlapsAny(peaks_p300, peaks_H3K27ac, type="within"))
overlap_H3K27me3 <- sum(overlapsAny(peaks_p300, peaks_H3K27me3, type="within"))

total_p300 <- length(peaks_p300)

percentages_H3K4me3  <- (overlap_H3K4me3 / total_p300) * 100
percentages_H3K4me1  <- (overlap_H3K4me1 / total_p300) * 100
percentages_H3K27ac  <- (overlap_H3K27ac / total_p300) * 100
percentages_H3K27me3 <- (overlap_H3K27me3 / total_p300) * 100
```

### Overlap report
```{r}
cat("Proportion of p300 peaks overlapping with histone marks:\n")
cat(sprintf("H3K4me3: %.2f%%\n", percentages_H3K4me3))
cat(sprintf("H3K4me1: %.2f%%\n", percentages_H3K4me1))
cat(sprintf("H3K27ac: %.2f%%\n", percentages_H3K27ac))
cat(sprintf("H3K27me3: %.2f%%\n", percentages_H3K27me3))
```